name: Metrics - Coding Habits

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Coding habits chart
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Asia/Kolkata
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update habits [skip ci]"
          filename: assets/coding-habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
